const fetch = require("node-fetch");

const apiKey = process.env.GEMINI_API_KEY || ""; 

const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

const researchQuery = async (userQuery) => {

  for (let retryCount = 0; retryCount <= 5; retryCount++) {
    try {
      const payload = {
        contents: [{ parts: [{ text: userQuery }] }],
        tools: [{ google_search: {} }] // Enable Google Search Grounding
      };

      const response = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-preview-09-2025:generateContent?key=${apiKey}`,
        {
          method: "POST",
          body: JSON.stringify(payload),
          headers: { "Content-Type": "application/json" },
        }
      );

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`API ${response.status}: ${errorText}`);
      }

      const result = await response.json();

      // Extract content safely
      const candidate = result.candidates?.[0];
      const answer = candidate?.content?.parts?.[0]?.text;

      const source = candidate?.groundingMetadata?.groundingAttributions?.map(
        (attr) => ({ 
          uri: attr.web?.uri, 
          title: attr.web?.title 
        })
      ) || [];

      if (!answer) {
        throw new Error("No response generated by the AI.");
      }

      return { answer, source };

    } catch (error) {
      if (retryCount < 5) {
        const delay = Math.pow(2, retryCount) * 1000;
        await wait(delay);
      } else {
        throw new Error(`Research Agent failed after 5 retries: ${error.message}`);
      }
    }
  }
};

module.exports = { researchQuery };